[package]
name = "turbo-genesis-sdk"
version = "1.2.2"
description = "Turbo Genesis SDK"
license = "MIT"
authors = ["@jozanza (hello@jsavary.com)"]
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
base64 = "0.21.2"
binary-layout = "3.2.0"
borsh = "0.10.3"
bytemuck = { version = "1.15.0", features = ["derive"], git = "https://github.com/super-turbo-society/bytemuck.git"}
structstruck = "0.4.1"
solana-sdk = { version = ">=1.17", optional = true }
paste = "1.0.14"

[features]
no-host = []
solana = ["solana-sdk"]
